config/routes.rb
Rails.application.routes.draw do
  resources :gomis
  resources :users

  root :to => 'users#index'

  post "login"  => "users#login"
  patch "login" => "users#login"

=begin

  constraints -> request { request.session[:user_id].present? } do
    root to: 'gomi#index', as: :user_root
  end
  root to: 'user#top'

  patch 'gomi/create' => 'gomi#create'

  get 'gomi/index'
  get 'gomi/show'
  get 'gomi/create'
  post "create" => "user#create"
  post "login"  => "user#login"

  post "user/create" => "user#create"

=end

end

app/models/gomi.rb
class Gomi < ActiveRecord::Base
  belongs_to :user
  # バリデーション
  # 値が存在　: true
  validates :name, :every, :user_id, presence: true

  # 条件付き
  validates :start_date, presence: true, if: :fortnightly?

  def fortnightly?
    every == 2
  end

  # カスタムバリデーション
  validate :select_one_day_of_the_week

  def select_one_day_of_the_week
    if mon + tues + wed + thurs + fri + sat + sun == 0
      errors.add(:曜日,":1つ以上の曜日を選択してください．")
    end
  end
end

app/controllers/gomi_controller.rb
class GomiController < ApplicationController

#  include SessionsHelper

  def gomi_params
    params.require(:gomi).permit(
        gomis_attributes: [:id, :name, :_destroy]
    )
  end

  def current_user
    @current_user ||= User.find_by(id: session[:id])
  end

  helper_method :current_user

  def top
    puts "user---"
    p @user
    session[:id] = @user.id
  end

  def index
    @user = current_user
  end

  def show
    @gomi = Gomi.where(user_id: current_user.id)
    puts "class"
    p @gomi
    puts ""
  end

  def check(num)
    num==1 ? true : false
  end

  def create

    @user = current_user
    hour = params[:user]["pushtime(4i)"].to_i
    min = params[:user]["pushtime(5i)"].to_i

    t = Time.local(2017,3,27,hour,min,0)
    @user.pushtime = t.to_s(:db)
    @user.title = params[:title]
    @user.save

    flash[:notice] = nil

    Gomi.delete_all(:user_id => current_user.id)

    puts "params:"

    data = ActionController::Parameters.new(params[:user][:gomis_attributes])

    puts "data------"
    data.each do |d|
      p d
    end

    puts "data------"

    keys = [:mon, :tues, :wed, :thurs, :fri, :sat, :sun]

#    gomis = []

    data.each do |id, gomi|
      if gomi[:_destroy]
        next
      end
      @gomi = Gomi.new
      @gomi.user_id = current_user.id

      @gomi.name = gomi[:name]

#      @gomi.every = (gomi[:every] == 1) ? true : false
      @gomi.every = gomi[:every]

#      if gomi[:every] == 1
        # どうにかして
        # その日が来たらチェックして更新して…
        @gomi.start_date = gomi[:start_date]
#      end

      keys.each do |key|
#        @gomi[key] = check(gomi[key])
        @gomi[key] = gomi[key]
      end

#      gomis << @gomi

      unless @gomi.save
        puts "失敗〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜"
        flash[:alert] = @gomi.errors.full_messages
       # 登録失敗時に入力データを保持する
        puts "gomi"
        p gomi
        @user.gomis.build(gomi)
#        @user.save

        flash[:notice] = nil
        render action: 'index' and return

#        @user = User.new(params[:user][:gomis_attributes])
#        attr = params.require(:user).permit(:name)
#        @gomi = Gomi.new(params.require(:user).permit(:name))
#        @gomi.save
      else
        puts "更新〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜〜"
        flash[:notice] = "更新しました"
      end

    end

=begin
    result = Gomi.import gomis

    puts "result"
    p result
    p result[:failed_instances]
    if result[:failed_instances].blank?
      # 成功
      flash[:notice] = "更新しました"
    else
      # 失敗
      res = result[:failed_instances].first
      puts "res"
      attr = res[:name]
#      attr = Hash[]
      p attr
      @user = current_user
#      result[:failed_instances].each do |attr|
#        @user = User.new({name:attr})
      p @user
      render action: 'index' and return
#      end
      end
=end


    redirect_to gomi_index_path
  end

end

app/controllers/gomis_controller.rb
class GomisController < ApplicationController
  before_action :set_gomi, only: [:show, :edit, :update, :destroy]

  def gomi_params
    params.require(:gomi).permit(
        gomis_attributes: [:id, :name, :_destroy]
    )
  end

  # viewでもcurrent_userメソッドが使えるようになる．すごーい
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:id])
  end

  # GET /gomis
  # GET /gomis.json
  def index
    @gomis = Gomi.all
  end

  # GET /gomis/1
  # GET /gomis/1.json
  def show
  end

  # GET /gomis/new
  def new
    @gomi = Gomi.new
  end

  # GET /gomis/1/edit
  def edit
  end

  # POST /gomis
  # POST /gomis.json
  def create
    @gomi = Gomi.new(gomi_params)

    respond_to do |format|
      if @gomi.save
        format.html { redirect_to @gomi, notice: 'Gomi was successfully created.' }
        format.json { render :show, status: :created, location: @gomi }
      else
        format.html { render :new }
        format.json { render json: @gomi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gomis/1
  # PATCH/PUT /gomis/1.json
  def update
    respond_to do |format|
      if @gomi.update(gomi_params)
        format.html { redirect_to @gomi, notice: 'Gomi was successfully updated.' }
        format.json { render :show, status: :ok, location: @gomi }
      else
        format.html { render :edit }
        format.json { render json: @gomi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gomis/1
  # DELETE /gomis/1.json
  def destroy
    @gomi.destroy
    respond_to do |format|
      format.html { redirect_to gomis_url, notice: 'Gomi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gomi
      @gomi = Gomi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
#    def gomi_params
#      params.require(:gomi).permit(:name, :every, :start_date, :mon, :tues, :wed, :thurs, :fri, :sat, :sun, :user_id)
#    end
end

app/helpers/gomi_helper.rb
module GomiHelper
end

app/helpers/gomis_helper.rb
module GomisHelper
end

app/views/gomis/_form.html.erb
<%= form_for(@gomi) do |f| %>
  <% if @gomi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gomi.errors.count, "error") %> prohibited this gomi from being saved:</h2>

      <ul>
      <% @gomi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :every %><br>
    <%= f.number_field :every %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :mon %><br>
    <%= f.number_field :mon %>
  </div>
  <div class="field">
    <%= f.label :tues %><br>
    <%= f.number_field :tues %>
  </div>
  <div class="field">
    <%= f.label :wed %><br>
    <%= f.number_field :wed %>
  </div>
  <div class="field">
    <%= f.label :thurs %><br>
    <%= f.number_field :thurs %>
  </div>
  <div class="field">
    <%= f.label :fri %><br>
    <%= f.number_field :fri %>
  </div>
  <div class="field">
    <%= f.label :sat %><br>
    <%= f.number_field :sat %>
  </div>
  <div class="field">
    <%= f.label :sun %><br>
    <%= f.number_field :sun %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gomis/edit.html.erb
<h1>Editing Gomi</h1>

<%= render 'form' %>

<%= link_to 'Show', @gomi %> |
<%= link_to 'Back', gomis_path %>

app/views/gomis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gomis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Every</th>
      <th>Start date</th>
      <th>Mon</th>
      <th>Tues</th>
      <th>Wed</th>
      <th>Thurs</th>
      <th>Fri</th>
      <th>Sat</th>
      <th>Sun</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gomis.each do |gomi| %>
      <tr>
        <td><%= gomi.name %></td>
        <td><%= gomi.every %></td>
        <td><%= gomi.start_date %></td>
        <td><%= gomi.mon %></td>
        <td><%= gomi.tues %></td>
        <td><%= gomi.wed %></td>
        <td><%= gomi.thurs %></td>
        <td><%= gomi.fri %></td>
        <td><%= gomi.sat %></td>
        <td><%= gomi.sun %></td>
        <td><%= gomi.user_id %></td>
        <td><%= link_to 'Show', gomi %></td>
        <td><%= link_to 'Edit', edit_gomi_path(gomi) %></td>
        <td><%= link_to 'Destroy', gomi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gomi', new_gomi_path %>

app/views/gomis/new.html.erb
<h1>New Gomi</h1>

<%= render 'form' %>

<%= link_to 'Back', gomis_path %>

app/views/gomis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gomi.name %>
</p>

<p>
  <strong>Every:</strong>
  <%= @gomi.every %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @gomi.start_date %>
</p>

<p>
  <strong>Mon:</strong>
  <%= @gomi.mon %>
</p>

<p>
  <strong>Tues:</strong>
  <%= @gomi.tues %>
</p>

<p>
  <strong>Wed:</strong>
  <%= @gomi.wed %>
</p>

<p>
  <strong>Thurs:</strong>
  <%= @gomi.thurs %>
</p>

<p>
  <strong>Fri:</strong>
  <%= @gomi.fri %>
</p>

<p>
  <strong>Sat:</strong>
  <%= @gomi.sat %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @gomi.sun %>
</p>

<p>
  <strong>User:</strong>
  <%= @gomi.user_id %>
</p>

<%= link_to 'Edit', edit_gomi_path(@gomi) %> |
<%= link_to 'Back', gomis_path %>